config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "flats#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController


  def index
  @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params[:flat])
    if
      @flat.save
      redirect_to flat_path
    else
      flash.alert = 'Impossible to create'
      redirect_to new_flat_path
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :adress, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1> Créer le form pour éditer</h1>

<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row"><h1> All My Flats</h1></div>
  <div class="row"> <p> All <%=  @flats.count %> flats available </p></div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-content">
            <div class="flat-card-title">
              <%= flat.name %>
            </div>
            <p><%= flat.adress %></p>
            <div class="flex">
              <div class="flex align-items-center">
              <i class="fa-solid fa-people-line"></i> <%= flat.number_of_guests %>
                <%= flat.price_per_night %> <i class="fa-solid fa-euro-sign"></i>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", flat_path(flat) %>
            <%= link_to "Edit", edit_flat_path(flat)%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1> Insérer simple form new</h1>


  <%# <%= form_with model: @restaurant do |f| %> %>
    <%# <%= f.label :name %>
    <%# <%= f.text_field :name %> %>
    <%# <%= f.label :address %> %>
    <%# <%= f.text_field :address %> %>
    <%# <%= f.label :rating %> %>
    <%# <%= f.number_field :rating %> %>
    <%# <%= f.submit %> %> %>
  <%# <% end %> %>

app/views/flats/show.html.erb
<h1> Faire la show d'un flat</h1>



<%= link_to "Delete",
  flat_path(@flat),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>